name: Pete Roome
description: Code Snippets and such like.
url: http://peteroome.com

stylus:
  compress: true
  path: ./css

paginate: 5
highlighter: "pygments"

sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
    - "/css/all.css"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"